import type { Metadata } from "next";
import { Cherry_Bomb_One, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const cherryBombOne = Cherry_Bomb_One({
	variable: "--font-cherry-bomb-one",
	subsets: ["latin"],
	weight: "400",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${cherryBombOne.variable} antialiased h-dvh`}
			>
				<div className="pt-6 pr-8 md:pt-8 md:pr-12 lg:text-xl justify-end flex text-[var(--secondary)] bg-[var(--primary)]">About me</div>
				{children}
			</body>
		</html>
	);
}
